### ISSUE TITLE
[Bug]: Fabric 1.19.2 / CTM is required on servers

### ISSUE THREAD

**Issue by ground-fruit** [CookieCNetwork/Chipped#172]
### Bug Description

CTM is client side only, so it shouldn't be required on the server.

[20:33:41] [main/ERROR]: Incompatible mod set
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
  Install ctm, any version.
Unmet dependency listing:
Mod 'Chipped' (chipped) 2.1.0 requires any version of ctm, which is missing!
  at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.14.jar:?]
  at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.14.jar:?]
  at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.14.jar:?]
  at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.14.jar:?]
  at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.14.jar:?]

### How to Reproduce?

1. Load chipped on a server without CTM
 -> server fails to start

### Expected Behavior

Server starts with chipped but not CTM installed.

### Version

2.1.0

### Mod Loader Version

Fabric 1.19.2 - 0.14.13

### Mod Loader

Fabric

### Logs or additional context

Full crash log:
https://mclo.gs/21acFWG

**Comment by Dekkan** [comment]
Also found this out last night trying to install. Had been waiting a while to see a fabric update to 1.19.2 and was super excited for it and then went looking for the ctm and realized it is a forge mod which clearly will not work with fabric.

**Comment by Treeways** [comment]
Can confirm the bug still exists for Quilt 1.20.1.

**Comment by CodexAdrian** [comment]
What? CTM is no longer a dependency as of 1.20?

**Comment by MimzyFang** [comment]
> What? CTM is no longer a dependency as of 1.20?

the issue is no longer with CTM it's now with athena

```
Chipped requires version [3.0.0, ∞) of athena, which is missing!

- <mods>/chipped-fabric-1.20.1-3.0.1.jar

```

issue should probably be remained

**Comment by CodexAdrian** [comment]
The problem is that we cannot physically do anything about this issue. Fabrics dependency system doesn’t allow us to specify on which side, client or server, something may be required or not. Something is either always required or always not required. To that end, we cannot make Athena only required on client. But Athena being the kind of mod that it is, shouldn’t affect your modpack at all if it’s loaded on a server, is Athena causing crashes when loaded on a pack? If that’s the case please open an issue with us about Athena breaking on servers, otherwise this issue is no longer relevant as we published a version of Chipped long ago with CTM as optional on fabric due to another issue with the CTM mod
