### ISSUE TITLE
[Bug]: New update incompatible with Sophisticated Backpacks

### ISSUE THREAD

**Issue by Blasg2** [CookieCNetwork/Chipped#269]
### Bug Description

You can't use both together even if its the only mods you're using.

Caused by: java.lang.NoSuchFieldError: BOTANIST_WORKBENCH_TYPE
		at net.p3pp3rf1y.sophisticatedbackpacks.compat.chipped.ChippedCompat.lambda$static$0(ChippedCompat.java:34) ~[sophisticatedbackpacks-1.20.1-3.19.5.988.jar%23164!/:1.20.1-3.19.5.988] {re:classloading}

### How to Reproduce?

Just use both mods.

### Version

3.0.2

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by dadadadaan** [comment]
This is actually likely to be on the sophisticated backpacks side now that I think about it - Sophisticated backpacks has a compat system built in for Chipped that just might need to be updated due to the GUI changes in the recent release. I work on neither teams so obviously I can't confirm, but it seems like a possibility. There's already an issue logged on the Sophisticated Backpacks side for the same issue here: https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/958

**Comment by AlexNijjar** [comment]
Yeah this is something they would need to fix. SB references code that no longer exists.

**Comment by ghost** [comment]
I looked at the crash-report it's the Botanist Workbench Upgrade Type for Sophisticated Backpacks.

**Comment by CodexAdrian** [comment]
The sophisticated backpacks dev is aware of the issue, we can’t do anything about it. Was told the issue will be fixed soon
